flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.2.1
- bson-0.1.7
- bson-generic-0.0.6
- compact-string-fix-0.3.2
- http-api-data-0.3.3
- mongoDB-1.2.0
- servant-0.9.1.1
- servant-client-0.9.1.1
- servant-server-0.9.1.1
resolver: lts-7.14
