
flags: {}
extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/Palmik/bson-generic.git
    commit: e078def65d0dee1ea7e3205f445e47d5937851f3
extra-deps: [servant-client-0.9.1.1, servant-0.9.1.1, servant-server-0.9.1.1, http-api-data-0.3.2]
resolver: lts-7.13
